/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.redbrick.medright.tracker.ui;

import static org.redbrick.medright.tracker.utils.DatabaseOps.connectToDB;

import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author RedBrick
 */
public class SecurityCheckGUI extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private Connection conn;
	private PreparedStatement ps;
	private ResultSet rs;
	private String secCheck;

	/**
	 * Creates new form SecurityCheckGUI
	 *
	 * @throws java.lang.ClassNotFoundException
	 * @throws java.lang.InstantiationException
	 * @throws java.lang.IllegalAccessException
	 * @throws java.sql.SQLException
	 */
	public SecurityCheckGUI() throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
		this.initComponents();

	}

	public void securityCheckClose() {

		WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
		Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPasswordField = new javax.swing.JPasswordField();
		Password = new javax.swing.JLabel();
		jTextFieldUserName = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		UserName = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setAlwaysOnTop(true);
		setBounds(new java.awt.Rectangle(200, 300, 0, 0));
		setLocation(new java.awt.Point(100, 200));
		setName("secCheckFrame"); // NOI18N
		addPropertyChangeListener(new java.beans.PropertyChangeListener() {
			@Override
			public void propertyChange(java.beans.PropertyChangeEvent evt) {
				formPropertyChange(evt);
			}
		});

		jPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPasswordField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordFieldActionPerformed(evt);
			}
		});

		Password.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
		Password.setText("Password");

		jTextFieldUserName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldUserNameActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
		jLabel1.setText("Please Enter Your Username and Password");

		UserName.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
		UserName.setText("UserName");

		btnSubmit = new JButton("Submit");
		btnSubmit.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
			}
		});
		btnSubmit.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				btnNewSubmitActionPerformed(e);
			}
		});

		GroupLayout layout = new GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(48)
						.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel1)
								.addGroup(layout.createSequentialGroup().addGap(32)
										.addGroup(layout.createParallelGroup(Alignment.TRAILING).addComponent(UserName)
												.addComponent(Password))
						.addGap(18)
						.addGroup(layout.createParallelGroup(Alignment.LEADING, false).addComponent(jTextFieldUserName)
								.addComponent(jPasswordField, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 120,
										Short.MAX_VALUE)
								.addComponent(btnSubmit, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addContainerGap(48, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(16).addComponent(jLabel1).addGap(25)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jTextFieldUserName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
						.addComponent(UserName, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jPasswordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(Password, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnSubmit)
				.addContainerGap(22, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		getAccessibleContext().setAccessibleName("secCheckFrame");
		getAccessibleContext().setAccessibleDescription("");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	protected void btnNewSubmitActionPerformed(ActionEvent e) {
		try {
			this.secCheck = "login";
			this.conn = connectToDB(this.secCheck);
			String query = "SELECT * FROM APP.USERS where UserName =? and Password=?";

			this.ps = this.conn.prepareStatement(query);
			this.ps.setString(1, this.jTextFieldUserName.getText());
			this.jPasswordField.selectAll();
			this.ps.setString(2, this.jPasswordField.getSelectedText());
			this.rs = this.ps.executeQuery();
			if (this.rs.next()) {
				JOptionPane.showMessageDialog(null, "Authenticated!");
				this.conn.close();
				MedRightStartGUI medgui;
				medgui = new MedRightStartGUI();
				medgui.setVisible(true);
				this.dispose();
			} else {

				JOptionPane.showMessageDialog(null, "Username or Password is Incorrecct ", "Access Denied! ",
						JOptionPane.ERROR_MESSAGE);
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
			Logger.getLogger(SecurityCheckGUI.class.getName()).log(Level.SEVERE, null, ex);

		}

	}

	private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldUserNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldUserNameActionPerformed

	private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jPasswordFieldActionPerformed

	private void formPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_formPropertyChange
		// TODO add your handling code here:
	}// GEN-LAST:event_formPropertyChange

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Metal".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;

				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SecurityCheckGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				try {
					new SecurityCheckGUI().setVisible(true);

				} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
					Logger.getLogger(SecurityCheckGUI.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	javax.swing.JLabel Password;
	javax.swing.JLabel UserName;
	javax.swing.JLabel jLabel1;
	javax.swing.JPasswordField jPasswordField;
	javax.swing.JTextField jTextFieldUserName;
	private JButton btnSubmit;
	// End of variables declaration//GEN-END:variables
}
