/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.redbrick.medright.tracker.ui;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Dimension;
import java.awt.Rectangle;

/**
 *
 * @author RedBrick
 */
public class SetUserTimesGUI extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form UserTimes
	 */
	public SetUserTimesGUI() {
		setPreferredSize(new Dimension(325, 384));
		setMinimumSize(new Dimension(320, 384));
		setMaximumSize(new Dimension(320, 384));
		setBounds(new Rectangle(0, 23, 325, 384));
		setSize(new Dimension(320, 384));
		setResizable(false);
		this.initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		AMHour = new javax.swing.JComboBox();
		AMMins = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		MidAMHour = new javax.swing.JComboBox();
		MidAMMins = new javax.swing.JComboBox();
		NoonHour = new javax.swing.JComboBox();
		NoonMins = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		MidAftHour = new javax.swing.JComboBox();
		MidAftMins = new javax.swing.JComboBox();
		AfternoonHour = new javax.swing.JComboBox();
		AfternoonMins = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		EveningHour = new javax.swing.JComboBox();
		EveningMins = new javax.swing.JComboBox();
		BedtimeHour = new javax.swing.JComboBox();
		BedtimeMins = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		MidOfNightHour = new javax.swing.JComboBox();
		MidOfNightMins = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
		jLabel9.setText("Set Event Time Defaults");

		AMHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7",
				"8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

		AMMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		jLabel1.setText("AM");

		jLabel2.setText("Mid AM");

		MidAMHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7",
				"8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

		MidAMMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		NoonHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7",
				"8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

		NoonMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		jLabel3.setText("Noon");

		jLabel4.setText("Mid Aft");

		MidAftHour.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7", "8", "9",
						"10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

		MidAftMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		AfternoonHour.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7", "8", "9",
						"10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));
		AfternoonHour.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AfternoonHourActionPerformed(evt);
			}
		});

		AfternoonMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		jLabel5.setText("Afternoon");

		jLabel6.setText("Evening");

		EveningHour.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7", "8", "9",
						"10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

		EveningMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		BedtimeHour.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7", "8", "9",
						"10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

		BedtimeMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		jLabel7.setText("Bedtime");

		jLabel8.setText("Middle of Night");

		MidOfNightHour.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "...", "1", "2", "3", "4", "5", "6", "7", "8", "9",
						"10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

		MidOfNightMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "00", "15", "30", "45" }));

		btnHelp = new JButton("Help");

		btnSave = new JButton("Save");

		btnExit = new JButton("Exit");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout
										.createParallelGroup(
												Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(30)
												.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
														.addComponent(jLabel1).addComponent(jLabel2)
														.addComponent(jLabel3).addComponent(jLabel4)
														.addComponent(jLabel5).addComponent(jLabel6)
														.addComponent(jLabel7).addComponent(jLabel8))
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(MidOfNightHour, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(BedtimeHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(EveningHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(AfternoonHour, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(MidAftHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(NoonHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(MidAMHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(AMHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(MidOfNightMins, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(BedtimeMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(EveningMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(AfternoonMins, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(MidAftMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(NoonMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(MidAMMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(AMMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)).addGap(172))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(58).addComponent(btnHelp)
								.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnSave)
								.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnExit))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(55).addComponent(jLabel9)))
				.addContainerGap(166, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup().addContainerGap().addComponent(jLabel9).addGap(18)
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(AMHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1))
								.addGap(5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(MidAMHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addGap(5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(NoonHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3))
								.addGap(5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(MidAftHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel4))
								.addGap(5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(AfternoonHour, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5))
								.addGap(5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(EveningHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel6))
								.addGap(5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(BedtimeHour, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel7))
								.addGap(5)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(MidOfNightHour, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel8)))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(AMMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(5)
								.addComponent(MidAMMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(5)
								.addComponent(NoonMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(5)
								.addComponent(MidAftMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(5)
								.addComponent(AfternoonMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(5)
								.addComponent(EveningMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(5)
								.addComponent(BedtimeMins, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(5).addComponent(MidOfNightMins, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
				.addGap(18).addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE).addComponent(btnHelp)
						.addComponent(btnSave).addComponent(btnExit))
				.addContainerGap(18, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 301, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void AfternoonHourActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AfternoonHourActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_AfternoonHourActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 *
	 * @throws java.lang.ClassNotFoundException
	 * @throws java.lang.InstantiationException
	 * @throws java.lang.IllegalAccessException
	 * @throws javax.swing.UnsupportedLookAndFeelException
	 */
	public static void main(String args[]) throws ClassNotFoundException, InstantiationException,
			IllegalAccessException, UnsupportedLookAndFeelException {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
			// for ( javax.swing.UIManager.LookAndFeelInfo info :
			// javax.swing.UIManager.getInstalledLookAndFeels () ) {
			// if ("Metal".equals ( info.getName () ) ) {
			// javax.swing.UIManager.setLookAndFeel ( info.getClassName () );
			// break;
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SetUserTimesGUI.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		// </editor-fold>
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new SetUserTimesGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox AMHour;
	private javax.swing.JComboBox AMMins;
	private javax.swing.JComboBox AfternoonHour;
	private javax.swing.JComboBox AfternoonMins;
	private javax.swing.JComboBox BedtimeHour;
	private javax.swing.JComboBox BedtimeMins;
	private javax.swing.JComboBox EveningHour;
	private javax.swing.JComboBox EveningMins;
	private javax.swing.JComboBox MidAMHour;
	private javax.swing.JComboBox MidAMMins;
	private javax.swing.JComboBox MidAftHour;
	private javax.swing.JComboBox MidAftMins;
	private javax.swing.JComboBox MidOfNightHour;
	private javax.swing.JComboBox MidOfNightMins;
	private javax.swing.JComboBox NoonHour;
	private javax.swing.JComboBox NoonMins;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private JButton btnHelp;
	private JButton btnSave;
	private JButton btnExit;
	// End of variables declaration//GEN-END:variables
}
